# Numpy matplotlib 활용 실습

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

## scalar, vector, matrix tensor

In [2]:
vector_x = np.arange(5)
print(vector_x[0:5:2])

[0 2 4]


In [3]:
matrix_A = np.arange(12).reshape(4,3)
print(np.diag(matrix_A))

[0 4 8]


In [4]:
Tensor_H = np.zeros((5,3,2))
Tensor_H[2:3,:,:] = 1
print(Tensor_H)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


## transpose, dot

In [5]:
matrix_B = np.arange(12).reshape(3,4)
print(np.transpose(matrix_B))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [6]:
def transpose(A):
    row = len(A)
    column = len(A[0])
    B = np.zeros(row*column).reshape(column, row)
    for i in range(row):
        for j in range(column):
            B[j,i] = A[i,j]
    return B
matrix_C =  np.arange(12).reshape(4,3)
print(matrix_C)
print(transpose(matrix_C))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0.  3.  6.  9.]
 [ 1.  4.  7. 10.]
 [ 2.  5.  8. 11.]]


In [7]:
def dot(A,B):
    Arow = int(len(A))
    Acolumn = int(len(A[0]))
    Brow = int(len(B))
    Bcolumn = int(len(B[0]))
    if Arow!=Bcolumn or Brow!=Acolumn:
        return "내적 불가능한 matrix 입니다"
    else:
        C = np.zeros(Arow*Bcolumn).reshape(Arow,Bcolumn)
        for i in range(Arow):
            for j in range(Bcolumn):
                for k in range(Acolumn):
                    C[i,j] += A[i,k]*B[k,j]
        return C
matrix_A = np.arange(12).reshape(3,4)
matrix_B = np.arange(12).reshape(4,3)
print(dot(matrix_A, matrix_B))
print(np.dot(matrix_A, matrix_B))

[[ 42.  48.  54.]
 [114. 136. 158.]
 [186. 224. 262.]]
[[ 42  48  54]
 [114 136 158]
 [186 224 262]]


## norm

In [8]:
vector_x = np.arange(9)
Matrix_A = np.arange(9).reshape(3,3)
print(vector_x)
print("vector_x의 L1 norm: ",np.linalg.norm(vector_x,1))
print("vector_x의 L2 norm: ",np.linalg.norm(vector_x,2))
print("Matrix_A의 L2 norm: ",np.linalg.norm(matrix_A, 'fro'))
def norm(A, order = {1,2,'fro'}):
    if A.ndim == 1:
        if order == 1:
            return np.sum(np.abs(A))
        elif order == 2:
            return np.sqrt(np.sum(A**2))
    else:
        return np.sqrt(np.sum(A**2))
print(norm(vector_x,1))
print(norm(vector_x,2))
print(norm(matrix_A,'fro'))

[0 1 2 3 4 5 6 7 8]
vector_x의 L1 norm:  36.0
vector_x의 L2 norm:  14.2828568570857
Matrix_A의 L2 norm:  22.494443758403985
36
14.2828568570857
22.494443758403985


## data Sacaling

In [9]:
def Normalization(A):
    return (A-np.min(A))/(np.max(A)-np.min(A))
def Standardization(A):
    return (A-np.mean(A))/np.std(A)
Matrix_A = np.arange(12).reshape(3,4)
print("Normalization Matrix_A: ", Normalization(matrix_A))
print("Standardization Matrix_A: ", Standardization(matrix_A))

Normalization Matrix_A:  [[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]
Standardization Matrix_A:  [[-1.59325501 -1.30357228 -1.01388955 -0.72420682]
 [-0.43452409 -0.14484136  0.14484136  0.43452409]
 [ 0.72420682  1.01388955  1.30357228  1.59325501]]
