In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [22]:
vector_x = np.arange(5)
print(vector_x[0:5:2])

[0 2 4]
0 2 4


In [12]:
matrix_A = np.arange(12).reshape(4,3)
print(np.diag(matrix_A))

[0 4 8]


In [29]:
Tensor_H = np.zeros((5,3,2))
Tensor_H[2:3,:,:] = 1
print(Tensor_H)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
